version: '3.9'

services:

  aiohttp:

    build:
      context: app/aiohttp_server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app/aiohttp_server:/code:cached
    environment:
      - HOSTS=http://flask_1:5000,http://flask_2:5000,http://flask_3:5000,http://flask_4:5000

  flask_1:
    build:
      context: app/flask_server
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./app/flask_server:/code/
      - ./app/flask_server:/root/.cache/
    environment:
      - ARCHITECTURE=resnet152
      - PORT=5000


  flask_2:
    build:
      context: app/flask_server
      dockerfile: Dockerfile
    volumes:
      - ./app/flask_server:/code/
      - ./app/flask_server:/root/.cache/
    environment:
      - ARCHITECTURE=resnet18
      - PORT=5000

  flask_3:
    build:
      context: app/flask_server
      dockerfile: Dockerfile
    volumes:
      - ./app/flask_server:/code/
      - ./app/flask_server:/root/.cache/
    environment:
      - ARCHITECTURE=resnet34
      - PORT=5000

  flask_4:
    build:
      context: app/flask_server
      dockerfile: Dockerfile
    volumes:
      - ./app/flask_server:/code/
      - ./app/flask_server:/root/.cache/
    environment:
      - ARCHITECTURE=resnet50
      - PORT=5000
